<?php if (!defined('BASEPATH')) exit('No direct script access allowed'); 

/**   
 *   
 *    
 * Original code at http://codeigniter.com/forums/viewreply/284919/   
 */

/*
| -------------------------------------------------------------------------
| CI Layout mimic RoR
| -------------------------------------------------------------------------
| http://codeigniter.com/forums/viewreply/284919/ 
|
*/
class Layout 
{ 
    
    private $CI;
    
    function index() {      
        $this->CI =& get_instance();

        // get default output generated by CI
        $output = $this->CI->output->get_output();
        $requested = '';
        if (isset($this->CI->layout)) {
            // this will be the requested layout
            if (!preg_match('/(.+).php$/', $this->CI->layout)) {
                $this->CI->layout .= '.php';
            }

            $requested = APPPATH . 'views/templates/' . $this->CI->layout;
        }
        /**
        * Excepcion para no cargar algun template en caso de sea algun metodo con ajax
        */
        if ( !$this->CI->input->is_ajax_request() ) {     
            // this is the default layout, use as fallback
            $default = APPPATH . 'views/templates/default.php';
            $layout = '';
            
            if (file_exists($requested)) {
                $layout = $this->CI->load->file($requested, true);
            }
            else {
                $layout = $this->CI->load->file($default, true);
            }

            $view = str_replace("{contenido_vista}", $output, $layout);
            
            // Se puede enviar al navegador HTML o PDF
            if( $this->CI->session->flashdata('pdf') ){ // Variable flash para saber si es impresión
                $this->CI->load->library('pdf');
                if( $this->CI->session->flashdata('watermark') ){
                    $watermark = $this->CI->session->flashdata('watermark');
                }else{
                    $watermark = null;
                }
                if( $this->CI->session->flashdata('pagesize') ){
                    $pagesize = $this->CI->session->flashdata('pagesize');
                }else{
                    $pagesize = "Letter";
                }
                $pdf = $this->CI->pdf->render($view, $pagesize, $watermark);
                $this->CI->output->set_content_type('application/pdf')->set_output($pdf);
            }else{
                $this->CI->output->set_output($view);
            }
        }
    }

}

?>